### ISSUE TITLE
rastre layer name copy

### ISSUE THREAD

**Issue by Timmarh** [GeoScripting-WUR/AdvancedRasterAnalysis#15]
In [this line](https://github.com/GeoScripting-WUR/AdvancedRasterAnalysis/blob/gh-pages/index.Rmd#L160C147-L160C147) the tutorial specifies that the name of a raster layer is copied to the result of the ndvi eqution. Apparently this is not the case (anymore?) at least with some students. Maybe this is legacy? We should check.

**Comment by GreatEmerald** [comment]
Fixed in #16
