### ISSUE TITLE
R Source

### ISSUE THREAD

**Issue by Davidswinkels** [GeoScripting-WUR/AdvancedRasterAnalysis#3]
Hi GeoScripting-WUR,
There is an unnecessary button in your example:

This part of code can be removed (around line 1436):
<button class="source R toggle btn btn-xs btn-primary">
<span class="glyphicon glyphicon-chevron-down"></span> R source
</button>
<pre style=""><code class="source r">par(mfrow = c(1, 1))</code></pre>

   Reasoning behind it:
The number of plots is kept the same in NDVI and VCF plot. Why change it in between. When nothing is done with it?
-- Just before:
1. NDVI
par(mfrow = c(3, 1))

-- Button(to be removed):
par(mfrow = c(1, 1))

-- Just after:
2. VCF
par(mfrow = c(3, 1))

**Comment by loicdtx** [comment]
Good practice for plotting parameters setting is:

```r
# Set parameters and store initial parameters as opar
opar <- par(mfrow = c(3, 1))
# Calls to plot()
plot()
plot()
plot()
# Reset parameters
par(opar)
```
