### ISSUE TITLE
chapter 9 suggestion R-mateys

### ISSUE THREAD

**Issue by futureplant** [GeoScripting-WUR/AdvancedRasterAnalysis#5]
In chapter 9, advanced raster analysis: Applying a raster sieve by clumping

The following code:

```
## Group raster cells into clumps based on the Queen's Case
if(!file.exists(fn <- "data/clumformask.grd")) {
  forestclumps <- clump(formask, directions=8, filename=fn)
} else {
  forestclumps <- raster(fn)
}

```
throws error:
Loading required namespace: igraph
Failed with error:  ‘there is no package called ‘igraph’’

Maybe include a check for the package and an install?

**Comment by GreatEmerald** [comment]
Fixed.
